# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TaskMasterio' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftLint'

  # Pods for TaskMasterio

  target 'TaskMasterioTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TaskMasterioUITests' do
    # Pods for testing
  end

end
